//go:build !nodocs
// +build !nodocs

// Package linkup provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package linkup

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for CreateResponsesInputModel.
const (
	LinkupDeep     CreateResponsesInputModel = "linkup-deep"
	LinkupStandard CreateResponsesInputModel = "linkup-standard"
)

// Defines values for ImageSearchResultDtoType.
const (
	Image ImageSearchResultDtoType = "image"
)

// Defines values for QuerySearchDtoDepth.
const (
	Deep     QuerySearchDtoDepth = "deep"
	Standard QuerySearchDtoDepth = "standard"
)

// Defines values for QuerySearchDtoOutputType.
const (
	SearchResults QuerySearchDtoOutputType = "searchResults"
	SourcedAnswer QuerySearchDtoOutputType = "sourcedAnswer"
	Structured    QuerySearchDtoOutputType = "structured"
)

// Defines values for TextSearchResultDtoType.
const (
	Text TextSearchResultDtoType = "text"
)

// CreateResponsesInput defines model for CreateResponsesInput.
type CreateResponsesInput struct {
	// Input The natural language question for which you want to retrieve context.
	Input map[string]interface{} `json:"input"`

	// Instructions Optional instructions to guide the response generation. It`s similar to a system message.
	Instructions *string `json:"instructions,omitempty"`

	// Model The model used to generate the response.`linkup-standard` returns results faster; `linkup-deep` takes longer but yields more comprehensive results.
	Model CreateResponsesInputModel `json:"model"`

	// Text Optional custom text format configuration.
	Text *ResponsesTextFormatInput `json:"text,omitempty"`
}

// CreateResponsesInputModel The model used to generate the response.`linkup-standard` returns results faster; `linkup-deep` takes longer but yields more comprehensive results.
type CreateResponsesInputModel string

// CreditDto defines model for CreditDto.
type CreditDto struct {
	// Balance The number of credits remaining in your account.
	Balance float32 `json:"balance"`
}

// FetchDto defines model for FetchDto.
type FetchDto struct {
	// ExtractImages Defines whether the API should extract the images from the webpage in its response.
	ExtractImages *bool `json:"extractImages,omitempty"`

	// IncludeRawHtml Defines whether the API should include the raw HTML of the webpage in its response.
	IncludeRawHtml *bool `json:"includeRawHtml,omitempty"`

	// RenderJs Defines whether the API should render the JavaScript of the webpage.
	RenderJs *bool `json:"renderJs,omitempty"`

	// Url The URL of the webpage you want to fetch.
	Url string `json:"url"`
}

// FetchImageDto defines model for FetchImageDto.
type FetchImageDto struct {
	// Alt The alt text of the image.
	Alt *string `json:"alt,omitempty"`

	// Url The URL of the image.
	Url string `json:"url"`
}

// FetchResponseDto defines model for FetchResponseDto.
type FetchResponseDto struct {
	// Images List of images extracted from the webpage.
	Images *[]FetchImageDto `json:"images,omitempty"`

	// Markdown The clean markdown version of the webpage.
	Markdown string `json:"markdown"`

	// RawHtml The raw HTML version of the webpage.
	RawHtml *string `json:"rawHtml,omitempty"`
}

// ImageSearchResultDto defines model for ImageSearchResultDto.
type ImageSearchResultDto struct {
	// Name The title or name of the resource.
	Name string `json:"name"`

	// Type The type of the resource.
	Type ImageSearchResultDtoType `json:"type"`

	// Url The URL of the resource.
	Url string `json:"url"`
}

// ImageSearchResultDtoType The type of the resource.
type ImageSearchResultDtoType string

// QuerySearchDto defines model for QuerySearchDto.
type QuerySearchDto struct {
	// Depth Defines the precision of the search. `standard` returns results faster; `deep` takes longer but yields more comprehensive results.
	Depth QuerySearchDtoDepth `json:"depth"`

	// ExcludeDomains The domains you want to exclude of the search. By default, don't restrict the search.
	ExcludeDomains *[]string `json:"excludeDomains,omitempty"`

	// FromDate The date from which the search results should be considered, in ISO 8601 format (YYYY-MM-DD). It must be before `toDate`, if provided, and later than 1970-01-01.
	FromDate *string `json:"fromDate,omitempty"`

	// IncludeDomains The domains you want to search on. By default, don't restrict the search. You can provide up to 100 domains.
	IncludeDomains *[]string `json:"includeDomains,omitempty"`

	// IncludeImages Defines whether the API should include images in its results.
	IncludeImages *bool `json:"includeImages,omitempty"`

	// IncludeInlineCitations Relevant only when `outputType` is `sourcedAnswer`. Defines whether the answer should include inline citations.
	IncludeInlineCitations *bool `json:"includeInlineCitations,omitempty"`

	// IncludeSources Relevant only when `outputType` is `structured`. Defines whether the response should include sources. **Please note that it modifies the schema of the response, see below**
	IncludeSources *bool `json:"includeSources,omitempty"`

	// MaxResults The maximum number of results to return.
	MaxResults *float32 `json:"maxResults,omitempty"`

	// OutputType The type of output you want to get. Use `structured` for a custom-formatted response defined by `structuredOutputSchema`.
	OutputType QuerySearchDtoOutputType `json:"outputType"`

	// Q The natural language question for which you want to retrieve context.
	Q string `json:"q"`

	// StructuredOutputSchema Required only when `outputType` is `structured`. Provide a JSON schema (as a string) representing the desired response format. The root must be of type `object`.
	StructuredOutputSchema json.RawMessage `json:"structuredOutputSchema,omitempty"`

	// ToDate The date until which the search results should be considered, in ISO 8601 format (YYYY-MM-DD). It must be later than `fromDate`, if provided, or than 1970-01-01.
	ToDate *string `json:"toDate,omitempty"`
}

// QuerySearchDtoDepth Defines the precision of the search. `standard` returns results faster; `deep` takes longer but yields more comprehensive results.
type QuerySearchDtoDepth string

// QuerySearchDtoOutputType The type of output you want to get. Use `structured` for a custom-formatted response defined by `structuredOutputSchema`.
type QuerySearchDtoOutputType string

// ResponsesTextFormatInput defines model for ResponsesTextFormatInput.
type ResponsesTextFormatInput struct {
	// Format Defines the response text format. Accepts the literal string `text` for plain text or a JSON schema object that describes the desired structured output.
	Format map[string]interface{} `json:"format"`
}

// SearchResultsDto defines model for SearchResultsDto.
type SearchResultsDto struct {
	// Results List of search results.
	Results []SearchResultsDto_Results_Item `json:"results"`
}

// SearchResultsDto_Results_Item defines model for SearchResultsDto.results.Item.
type SearchResultsDto_Results_Item struct {
	union json.RawMessage
}

// SourceDto defines model for SourceDto.
type SourceDto struct {
	// Favicon The favicon URL of the source, if available.
	Favicon string `json:"favicon"`

	// Name The name or title of the source.
	Name string `json:"name"`

	// Snippet Extracted text content associated with the source.
	Snippet string `json:"snippet"`

	// Url The URL of the source.
	Url string `json:"url"`
}

// SourcedAnswerDto defines model for SourcedAnswerDto.
type SourcedAnswerDto struct {
	// Answer The answer to your question.
	Answer string `json:"answer"`

	// Sources List of sources used to answer the question.
	Sources []SourceDto `json:"sources"`
}

// StructuredWithSourcesDto defines model for StructuredWithSourcesDto.
type StructuredWithSourcesDto struct {
	// Data The object corresponding to the JSON schema you used in the `structuredOutputSchema` param.
	Data map[string]interface{} `json:"data"`

	// Sources List of sources used to answer the question.
	Sources []struct {
		// Content Extracted text content associated with the source.
		Content *string `json:"content,omitempty"`

		// Name The name or title of the source.
		Name *string `json:"name,omitempty"`

		// Type The type of the source.
		Type *string `json:"type,omitempty"`

		// Url The URL of the source.
		Url *string `json:"url,omitempty"`
	} `json:"sources"`
}

// TextSearchResultDto defines model for TextSearchResultDto.
type TextSearchResultDto struct {
	// Content Extracted text content associated with the resource.
	Content string `json:"content"`

	// Favicon The favicon URL of the resource, if available.
	Favicon string `json:"favicon"`

	// Name The title or name of the resource.
	Name string `json:"name"`

	// Type The type of the resource.
	Type TextSearchResultDtoType `json:"type"`

	// Url The URL of the resource.
	Url string `json:"url"`
}

// TextSearchResultDtoType The type of the resource.
type TextSearchResultDtoType string

// FetchJSONRequestBody defines body for Fetch for application/json ContentType.
type FetchJSONRequestBody = FetchDto

// ResponsesJSONRequestBody defines body for Responses for application/json ContentType.
type ResponsesJSONRequestBody = CreateResponsesInput

// SearchJSONRequestBody defines body for Search for application/json ContentType.
type SearchJSONRequestBody = QuerySearchDto

// AsTextSearchResultDto returns the union data inside the SearchResultsDto_Results_Item as a TextSearchResultDto
func (t SearchResultsDto_Results_Item) AsTextSearchResultDto() (TextSearchResultDto, error) {
	var body TextSearchResultDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextSearchResultDto overwrites any union data inside the SearchResultsDto_Results_Item as the provided TextSearchResultDto
func (t *SearchResultsDto_Results_Item) FromTextSearchResultDto(v TextSearchResultDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextSearchResultDto performs a merge with any union data inside the SearchResultsDto_Results_Item, using the provided TextSearchResultDto
func (t *SearchResultsDto_Results_Item) MergeTextSearchResultDto(v TextSearchResultDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageSearchResultDto returns the union data inside the SearchResultsDto_Results_Item as a ImageSearchResultDto
func (t SearchResultsDto_Results_Item) AsImageSearchResultDto() (ImageSearchResultDto, error) {
	var body ImageSearchResultDto
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageSearchResultDto overwrites any union data inside the SearchResultsDto_Results_Item as the provided ImageSearchResultDto
func (t *SearchResultsDto_Results_Item) FromImageSearchResultDto(v ImageSearchResultDto) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageSearchResultDto performs a merge with any union data inside the SearchResultsDto_Results_Item, using the provided ImageSearchResultDto
func (t *SearchResultsDto_Results_Item) MergeImageSearchResultDto(v ImageSearchResultDto) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SearchResultsDto_Results_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SearchResultsDto_Results_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Balance request
	Balance(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FetchWithBody request with any body
	FetchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Fetch(ctx context.Context, body FetchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResponsesWithBody request with any body
	ResponsesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Responses(ctx context.Context, body ResponsesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchWithBody request with any body
	SearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Search(ctx context.Context, body SearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Balance(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBalanceRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FetchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFetchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Fetch(ctx context.Context, body FetchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFetchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResponsesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResponsesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Responses(ctx context.Context, body ResponsesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResponsesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Search(ctx context.Context, body SearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBalanceRequest generates requests for Balance
func NewBalanceRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/credits/balance")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFetchRequest calls the generic Fetch builder with application/json body
func NewFetchRequest(server string, body FetchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFetchRequestWithBody(server, "application/json", bodyReader)
}

// NewFetchRequestWithBody generates requests for Fetch with any type of body
func NewFetchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/fetch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewResponsesRequest calls the generic Responses builder with application/json body
func NewResponsesRequest(server string, body ResponsesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewResponsesRequestWithBody(server, "application/json", bodyReader)
}

// NewResponsesRequestWithBody generates requests for Responses with any type of body
func NewResponsesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/responses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchRequest calls the generic Search builder with application/json body
func NewSearchRequest(server string, body SearchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSearchRequestWithBody(server, "application/json", bodyReader)
}

// NewSearchRequestWithBody generates requests for Search with any type of body
func NewSearchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// BalanceWithResponse request
	BalanceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BalanceResponse, error)

	// FetchWithBodyWithResponse request with any body
	FetchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FetchResponse, error)

	FetchWithResponse(ctx context.Context, body FetchJSONRequestBody, reqEditors ...RequestEditorFn) (*FetchResponse, error)

	// ResponsesWithBodyWithResponse request with any body
	ResponsesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResponsesResponse, error)

	ResponsesWithResponse(ctx context.Context, body ResponsesJSONRequestBody, reqEditors ...RequestEditorFn) (*ResponsesResponse, error)

	// SearchWithBodyWithResponse request with any body
	SearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchResponse, error)

	SearchWithResponse(ctx context.Context, body SearchJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchResponse, error)
}

type BalanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreditDto
}

// Status returns HTTPResponse.Status
func (r BalanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BalanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FetchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FetchResponseDto
}

// Status returns HTTPResponse.Status
func (r FetchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FetchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResponsesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ResponsesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResponsesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SearchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// BalanceWithResponse request returning *BalanceResponse
func (c *ClientWithResponses) BalanceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BalanceResponse, error) {
	rsp, err := c.Balance(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBalanceResponse(rsp)
}

// FetchWithBodyWithResponse request with arbitrary body returning *FetchResponse
func (c *ClientWithResponses) FetchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FetchResponse, error) {
	rsp, err := c.FetchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFetchResponse(rsp)
}

func (c *ClientWithResponses) FetchWithResponse(ctx context.Context, body FetchJSONRequestBody, reqEditors ...RequestEditorFn) (*FetchResponse, error) {
	rsp, err := c.Fetch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFetchResponse(rsp)
}

// ResponsesWithBodyWithResponse request with arbitrary body returning *ResponsesResponse
func (c *ClientWithResponses) ResponsesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResponsesResponse, error) {
	rsp, err := c.ResponsesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResponsesResponse(rsp)
}

func (c *ClientWithResponses) ResponsesWithResponse(ctx context.Context, body ResponsesJSONRequestBody, reqEditors ...RequestEditorFn) (*ResponsesResponse, error) {
	rsp, err := c.Responses(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResponsesResponse(rsp)
}

// SearchWithBodyWithResponse request with arbitrary body returning *SearchResponse
func (c *ClientWithResponses) SearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchResponse, error) {
	rsp, err := c.SearchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchResponse(rsp)
}

func (c *ClientWithResponses) SearchWithResponse(ctx context.Context, body SearchJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchResponse, error) {
	rsp, err := c.Search(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchResponse(rsp)
}

// ParseBalanceResponse parses an HTTP response from a BalanceWithResponse call
func ParseBalanceResponse(rsp *http.Response) (*BalanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BalanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreditDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFetchResponse parses an HTTP response from a FetchWithResponse call
func ParseFetchResponse(rsp *http.Response) (*FetchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FetchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FetchResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseResponsesResponse parses an HTTP response from a ResponsesWithResponse call
func ParseResponsesResponse(rsp *http.Response) (*ResponsesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResponsesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseSearchResponse parses an HTTP response from a SearchWithResponse call
func ParseSearchResponse(rsp *http.Response) (*SearchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
